apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-sts
spec:
  selector:
    matchLabels:
      app: wordpress # has to match .spec.template.metadata.labels
  serviceName: wordpress
  replicas: 5 # by default is 1
  template:
    metadata:
      labels:
        app: wordpress # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
          name: web